"""add novos campos

Revision ID: 160a60c28c10
Revises: 6e56c2cac6b7
Create Date: 2025-09-06 11:52:38.401652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '160a60c28c10'
down_revision = '6e56c2cac6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user', sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('user', sa.Column('data_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_nascimento')
    op.drop_column('user', 'telefone')
    
    # ### end Alembic commands ###
