"""add veiculos

Revision ID: 4a277c2bd802
Revises: f6ea99ce0e86
Create Date: 2025-09-14 22:26:12.670660

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4a277c2bd802'
down_revision = 'f6ea99ce0e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categorias_veiculo',
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'veiculos_base',
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('deleted_by', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('motor', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('versao', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('transmissao_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column('transmissao_velocidades', sa.Integer(), nullable=True),
        sa.Column('ar_condicionado', sa.Boolean(), nullable=True),
        sa.Column('direcao_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column('combustivel_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column('emissoes_nmhc', sa.Float(), nullable=True),
        sa.Column('emissoes_co', sa.Float(), nullable=True),
        sa.Column('emissoes_nox', sa.Float(), nullable=True),
        sa.Column('reducao_relativa_limite', sa.Float(), nullable=True),
        sa.Column('co2_fossil_etanol', sa.Float(), nullable=True),
        sa.Column('co2_fossil_gasolina', sa.Float(), nullable=True),
        sa.Column('km_l_etanol_cidade', sa.Float(), nullable=True),
        sa.Column('km_l_etanol_estrada', sa.Float(), nullable=True),
        sa.Column('km_l_gasolina_cidade', sa.Float(), nullable=True),
        sa.Column('km_l_gasolina_estrada', sa.Float(), nullable=True),
        sa.Column('consumo_energetico', sa.Float(), nullable=True),
        sa.Column('classificacao_pbe_relativa', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('classificacao_pbe_absoluta', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('selo_conpet', sa.Boolean(), nullable=True),
        sa.Column('quantidade_portas', sa.Integer(), nullable=True),
        sa.Column('categoria_externa', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('categoria_interna', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos_base')
    op.drop_table('categorias_veiculo')
    # ### end Alembic commands ###
