"""removido perfil

Revision ID: 6e56c2cac6b7
Revises: ad59536b9516
Create Date: 2025-09-06 10:09:47.942263

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e56c2cac6b7'
down_revision = 'ad59536b9516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfis', sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.drop_constraint(op.f('perfis_user_id_fkey'), 'perfis', type_='foreignkey')
    op.drop_column('perfis', 'user_id')
    op.add_column('schemas', sa.Column('teste', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('user', sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'genero')
    op.drop_column('schemas', 'teste')
    op.add_column('perfis', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('perfis_user_id_fkey'), 'perfis', 'user', ['user_id'], ['id'])
    op.drop_column('perfis', 'genero')
    # ### end Alembic commands ###
