"""ajuste usuario

Revision ID: ae519d69a367
Revises: 4a277c2bd802
Create Date: 2025-09-16 23:19:53.169550

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae519d69a367'
down_revision = '4a277c2bd802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status_corrida', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status_corrida')

    # ### end Alembic commands ###
