"""add veiculos

Revision ID: f6ea99ce0e86
Revises: fa48fcf14ad0
Create Date: 2025-09-14 21:06:36.321414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6ea99ce0e86'
down_revision = 'fa48fcf14ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos_motoristas',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_motoristas_placa'), 'veiculos_motoristas', ['placa'], unique=True)
    op.add_column('user', sa.Column('veiculo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'veiculos_motoristas', ['veiculo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'veiculo_id')
    op.drop_index(op.f('ix_veiculos_motoristas_placa'), table_name='veiculos_motoristas')
    op.drop_table('veiculos_motoristas')
    # ### end Alembic commands ###
