"""campos motorista

Revision ID: fa48fcf14ad0
Revises: 160a60c28c10
Create Date: 2025-09-10 18:19:12.850764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa48fcf14ad0'
down_revision = '160a60c28c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('current_lon', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_available')
    op.drop_column('user', 'current_lon')
    op.drop_column('user', 'current_lat')

    # ### end Alembic commands ###
