"""inicio

Revision ID: 257c57d2ec5c
Revises: 
Create Date: 2025-09-21 00:04:32.188926

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '257c57d2ec5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_corridas',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_veiculo',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_atividade',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('detalhe', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_corrida', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=True),
    sa.Column('cnh', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cnh_arquivo', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('foto_rosto', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('veiculos_base',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('motor', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('versao', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('transmissao_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('transmissao_velocidades', sa.Integer(), nullable=True),
    sa.Column('ar_condicionado', sa.Boolean(), nullable=True),
    sa.Column('direcao_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('combustivel_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('emissoes_nmhc', sa.Float(), nullable=True),
    sa.Column('emissoes_co', sa.Float(), nullable=True),
    sa.Column('emissoes_nox', sa.Float(), nullable=True),
    sa.Column('reducao_relativa_limite', sa.Float(), nullable=True),
    sa.Column('co2_fossil_etanol', sa.Float(), nullable=True),
    sa.Column('co2_fossil_gasolina', sa.Float(), nullable=True),
    sa.Column('km_l_etanol_cidade', sa.Float(), nullable=True),
    sa.Column('km_l_etanol_estrada', sa.Float(), nullable=True),
    sa.Column('km_l_gasolina_cidade', sa.Float(), nullable=True),
    sa.Column('km_l_gasolina_estrada', sa.Float(), nullable=True),
    sa.Column('consumo_energetico', sa.Float(), nullable=True),
    sa.Column('classificacao_pbe_relativa', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('classificacao_pbe_absoluta', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('selo_conpet', sa.Boolean(), nullable=True),
    sa.Column('quantidade_portas', sa.Integer(), nullable=True),
    sa.Column('categoria_externa', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('categoria_interna', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos_motoristas',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crlv', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('crlv_arquivo', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('foto_carro', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriados',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('abrangencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriados')
    op.drop_table('veiculos_motoristas')
    op.drop_table('veiculos_base')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('municipios')
    op.drop_table('log_atividade')
    op.drop_table('enderecos')
    op.drop_table('categorias_veiculo')
    op.drop_table('categorias_corridas')
    # ### end Alembic commands ###
