"""fk motorista veiculo

Revision ID: 1f0bff74915b
Revises: 257c57d2ec5c
Create Date: 2025-09-21 00:34:59.956087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f0bff74915b'
down_revision = '257c57d2ec5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos_motoristas',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('crlv', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('foto_carro', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'motorista_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos_motoristas', schema='public')
    # ### end Alembic commands ###
