"""5

Revision ID: e39c811a3934
Revises: 63ba62313fbd
Create Date: 2025-09-21 15:50:42.363966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e39c811a3934'
down_revision: Union[str, Sequence[str], None] = '63ba62313fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos_motoristas', sa.Column('crlv_arquivo', sa.String(length=1000), nullable=True))
    op.add_column('veiculos_motoristas', sa.Column('foto_carro', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos_motoristas', 'foto_carro')
    op.drop_column('veiculos_motoristas', 'crlv_arquivo')
    # ### end Alembic commands ###
