"""4

Revision ID: 63ba62313fbd
Revises: b5e81839964d
Create Date: 2025-09-21 15:49:14.361615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '63ba62313fbd'
down_revision: Union[str, Sequence[str], None] = 'b5e81839964d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos_motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('crlv', sa.String(length=1000), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'motorista_id')
    )
    op.create_index(op.f('ix_veiculos_motoristas_id'), 'veiculos_motoristas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_motoristas_id'), table_name='veiculos_motoristas')
    op.drop_table('veiculos_motoristas')
    # ### end Alembic commands ###
