"""empty message

Revision ID: a860633fd3c2
Revises: b198309a10fb
Create Date: 2025-09-26 22:08:42.400094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a860633fd3c2'
down_revision: Union[str, Sequence[str], None] = 'b198309a10fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos_motoristas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('crlv', sa.String(length=1000), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('crlv_arquivo', sa.String(length=1000), nullable=True),
    sa.Column('foto_carro', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_motoristas_id'), 'veiculos_motoristas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_motoristas_id'), table_name='veiculos_motoristas')
    op.drop_table('veiculos_motoristas')
    # ### end Alembic commands ###
