"""3

Revision ID: b5e81839964d
Revises: 42bf01a15100
Create Date: 2025-09-21 15:44:43.644490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b5e81839964d'
down_revision: Union[str, Sequence[str], None] = '42bf01a15100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('veiculo_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('logradouro', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('numero', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('complemento', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bairro', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('cidade', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('estado', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'estado')
    op.drop_column('users', 'cidade')
    op.drop_column('users', 'cep')
    op.drop_column('users', 'bairro')
    op.drop_column('users', 'complemento')
    op.drop_column('users', 'numero')
    op.drop_column('users', 'logradouro')
    op.drop_column('users', 'veiculo_id')
    # ### end Alembic commands ###
