"""empty message

Revision ID: 123bdf908429
Revises: 34975635b01f
Create Date: 2025-09-26 21:48:55.125994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '123bdf908429'
down_revision: Union[str, Sequence[str], None] = '34975635b01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos_motoristas', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_veiculos_motoristas_id'), 'veiculos_motoristas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_motoristas_id'), table_name='veiculos_motoristas')
    op.drop_column('veiculos_motoristas', 'id')
    # ### end Alembic commands ###
