"""empty message

Revision ID: 34975635b01f
Revises: ddd493eb0b1d
Create Date: 2025-09-26 21:47:55.750854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '34975635b01f'
down_revision: Union[str, Sequence[str], None] = 'ddd493eb0b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_motoristas_id'), table_name='veiculos_motoristas')
    op.drop_column('veiculos_motoristas', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos_motoristas', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_veiculos_motoristas_id'), 'veiculos_motoristas', ['id'], unique=False)
    # ### end Alembic commands ###
