"""6

Revision ID: ddd493eb0b1d
Revises: e39c811a3934
Create Date: 2025-09-21 17:56:47.412208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ddd493eb0b1d'
down_revision: Union[str, Sequence[str], None] = 'e39c811a3934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registry_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('registry_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registry_approved')
    op.drop_column('users', 'registry_completed')
    # ### end Alembic commands ###
