"""fk user perfil

Revision ID: 2fda99236e35
Revises: 8d8c2441ef39
Create Date: 2025-07-24 16:04:38.318612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2fda99236e35'
down_revision = '8d8c2441ef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=True),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hash', sa.Uuid(), nullable=False),
    sa.Column('status_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_hash'), 'perfis', ['hash'], unique=True)
    op.create_table('enderecos',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('log_atividade', sa.Column('perfil_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'log_atividade', 'perfis', ['perfil_id'], ['id'])
    op.add_column('user', sa.Column('perfil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'perfis', ['perfil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'perfil_id')
    op.drop_constraint(None, 'log_atividade', type_='foreignkey')
    op.drop_column('log_atividade', 'perfil_id')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_perfis_hash'), table_name='perfis')
    op.drop_table('perfis')
    # ### end Alembic commands ###
